version: '3'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: node:lts
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    network_mode: service:pocketbase

  pocketbase:
    container_name: ${COMPOSE_PROJECT_NAME}-pocketbase
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pb-data:/pb/pb_data

volumes:
  pb-data:
